SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

/* Table Setup Script */
CREATE TABLE dbo.deploy_log ( 
    id INT IDENTITY(1,1), 
    ts DATETIMEOFFSET DEFAULT sysdatetimeoffset(), 
    v NVARCHAR(10))
WITH (DATA_COMPRESSION = ROW);
